#!/usr/bin/env node
//@ts-check
/**
 * Usage: node scripts/build-tier3.js <extension-folder-name>
 *
 * For a Tier 3 extension (has extensions/<name>/code/index.ts):
 *   1. runs `node scripts/generate-extension.js <name>` first, so the JSON
 *      structure (actions/conditions/params) is fresh,
 *   2. bundles code/index.ts with tsup into a single IIFE attached to
 *      `window.<GlobalName>`,
 *   3. injects that bundle as the inlineCode of the extension's
 *      "onFirstSceneLoaded" function, so the whole module is defined once
 *      when the game starts and every other action/condition can call into
 *      it (window.<GlobalName>.something(...)) - the same pattern proven in
 *      THNK, WebSocketClient, Raycaster3D, EncryptedStorage and A3F.
 *
 * This mirrors THNK's own scripts/generate-extensions.js, generalized to
 * work for any extension in this kit instead of being hardcoded to one.
 */
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const extName = process.argv[2];
if (!extName) {
  console.error("Usage: node scripts/build-tier3.js <extension-folder-name>");
  process.exit(1);
}

const extDir = path.join(__dirname, "..", "extensions", extName);
const codeEntry = path.join(extDir, "code", "index.ts");
const extensionJsonPath = path.join(extDir, "extension.json");
const distDir = path.join(extDir, "dist");

if (!fs.existsSync(codeEntry)) {
  console.error(
    `${codeEntry} not found. Tier 3 extensions need a code/index.ts entry point.`
  );
  process.exit(1);
}

// 1. Regenerate the JSON structure from definition.js first.
execSync(`node "${path.join(__dirname, "generate-extension.js")}" ${extName}`, {
  stdio: "inherit",
});

// The global name every action/condition in definition.js should call into,
// e.g. window.MyExtension.doThing(...). Convention: same as the folder name,
// PascalCased. Override by exporting `globalName` from definition.js if needed.
delete require.cache[require.resolve(path.join(extDir, "definition.js"))];
const definitionModule = require(path.join(extDir, "definition.js"));
const globalName =
  definitionModule.globalName ||
  extName.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());

// 2. Bundle code/index.ts into a single IIFE global.
execSync(
  `npx tsup "${codeEntry}" --format iife --platform browser --global-name ${globalName} --minify --out-dir "${distDir}"`,
  { stdio: "inherit" }
);

const bundlePath = path.join(distDir, "index.global.js");
const bundleCode = fs.readFileSync(bundlePath, "utf8");

// 3. Inject the bundle into the onFirstSceneLoaded function's inlineCode.
const extensionJson = JSON.parse(fs.readFileSync(extensionJsonPath, "utf8"));
const bootstrap = extensionJson.eventsFunctions.find(
  (fn) => fn.name === "onFirstSceneLoaded"
);
if (!bootstrap) {
  console.error(
    `No "onFirstSceneLoaded" function found in extensions/${extName}/extension.json. ` +
      "Tier 3 extensions need one (see extensions/example-tier3/definition.js)."
  );
  process.exit(1);
}
bootstrap.events[0].inlineCode = [
  `// Load ${extName} (${globalName}) - generated by scripts/build-tier3.js, do not hand-edit`,
  bundleCode,
];

fs.writeFileSync(extensionJsonPath, JSON.stringify(extensionJson, null, 2) + "\n");
fs.rmSync(distDir, { recursive: true, force: true });

console.log(`Bundled code/index.ts into extensions/${extName}/extension.json as window.${globalName}`);
